### PR TITLE
Proposing a license file and changes

### PR DESCRIPTION
**Pull request by Luxcium**
Proposing a license file If you accept the proposal after the review it will help me show the copyright holder of your code into my project [Pop N' Lock Theme by Luxcium ✨](https://github.com/luxcium/pop-n-lock-theme-vscode)

### CODE REVIEW

**Comment by Luxcium** [comment]
please review and update any useful information as you please... 
e.g. Your name and the years

**Review by hedinne — APPROVED** [review]

**Comment by hedinne** [comment]
Thank you. I totally forgot to add the licence.

**Comment by Luxcium** [comment]
#### I am at **7690 installs** Thanks again for the inspiration ...

I did a mock-up of your example so you can compare both 😄 its still the same family for sure they have something similar ... 


Capture d’écran, le 2019-10-25 à 23 17 09
Capture d’écran, le 2019-10-25 à 23 12 19

**Comment by hedinne** [comment]
Nice! Getting a lot of downloads is always fun.

**Pull request merged**
